#  ******************************************************公共***********************************
# IP+端口
ip: http://172.21.129.200:8088

headers: {'content-Type': 'application/json;charset=UTF-8'}

#  ******************************************************运营后台****************************************************
# 运营后台：登录接口
login: /ai/auth/login

# 运营后台：登录账号
username: 15727125822
password: 123456789






